Completed css-positioning exercise -Julie Dumbrique
juliedumbrique/c0821-code-solutions pull request #18
Opened 2021-08-20 20:30 UTC by juliedumbrique

<img width="1090" alt="Screen Shot 2021-08-20 at 10 57 57 AM" src="https://user-images.githubusercontent.com/72038937/130290281-2b65d8da-6b3e-4524-b9fc-fad4ee05b3a1.png">
<img width="1090" alt="Screen Shot 2021-08-20 at 1 23 24 PM" src="https://user-images.githubusercontent.com/72038937/130290293-044417cd-e729-4b78-90d9-db05c6d21214.png">

2021-08-20 21:54 UTC, codingcodymiller requested changes
Nice start here!! A few notes for you:

2021-08-20 21:54 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  width: 250px;
Oh no! What happened here? You shouldn't need negatives values here, and you shouldn't need to set a width 🤔

2021-08-20 21:54 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  top: 166px;
This is a _**big**_ movement. Instead of moving this from the top, you should try starting from the `bottom`

2021-08-20 21:54 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  left: -45px;
😱 😱 😱 😱 

No negative values, please 🙏

2021-08-20 21:54 UTC, codingcodymiller commented on css-positioning/relative.css
> +}
You can remove the `relative` on each of these individual rules, you already applied it to all of these elements using the `.pokemon > img` rule above 🤓

2021-08-20 23:44 UTC, juliedumbrique commented
<img width="1104" alt="Screen Shot 2021-08-20 at 4 35 41 PM" src="https://user-images.githubusercontent.com/72038937/130303007-29f220ed-9da1-45ec-852b-cdcdd6d372a1.png">
<img width="1104" alt="Screen Shot 2021-08-20 at 4 35 49 PM" src="https://user-images.githubusercontent.com/72038937/130303011-8ad6f671-eb43-48cd-ba10-92449193ceb9.png">

https://user-images.githubusercontent.com/72038937/130303048-a42a45d9-13f9-42bd-b678-66feed646ea4.mov

2021-08-21 00:07 UTC, codingcodymiller approved these changes
Great work!!

2021-08-21 00:28 UTC, merged