Completed javascript-primitives-and-variables exercise - Julie Dumbrique
juliedumbrique/c0821-code-solutions pull request #21
Opened 2021-08-23 17:48 UTC by juliedumbrique

<img width="566" alt="Screen Shot 2021-08-23 at 10 46 03 AM" src="https://user-images.githubusercontent.com/72038937/130493262-4d42ee2f-0738-4a14-87f6-652c88e41418.png">

2021-08-23 17:51 UTC, codingcodymiller requested changes

2021-08-23 17:51 UTC, codingcodymiller commented on javascript-primitives-and-variables/main.js
> +console.log(typeof never);
![image](https://user-images.githubusercontent.com/32880187/130493657-de41415d-55cb-4da4-bf71-f6d7038a1f60.png)

2021-08-23 17:51 UTC, codingcodymiller commented on javascript-primitives-and-variables/main.js
> +console.log(typeof 1);
You shouldn't be logging out the value you assigned to the variable directly, you should be logging out the variable itself.

2021-08-24 03:27 UTC, juliedumbrique commented
<img width="539" alt="Screen Shot 2021-08-23 at 8 24 18 PM" src="https://user-images.githubusercontent.com/72038937/130551111-cd43f507-1d23-45dd-b434-8a3be75c0300.png">

2021-08-24 16:27 UTC, codingcodymiller approved these changes

2021-08-24 16:54 UTC, merged