Completed html-forms exercise - Julie Dumbrique
juliedumbrique/c0821-code-solutions pull request #7
Opened 2021-08-17 21:55 UTC by juliedumbrique

https://user-images.githubusercontent.com/72038937/129805781-4c587c4c-0943-42bf-8758-eb48a27032a7.mov

2021-08-17 22:00 UTC, codingcodymiller requested changes
Great start here!! A few notes for you:

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="email">Email</label>
This `for` attribute here is correct, but the form control element it is paired with needs a matching `id` attribute with the same value.

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="cool">Why is coding cool?</label>
This `for` attribute here is correct, but the form control element it is paired with needs a matching `id` attribute with the same value.

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="choose">Favorite Language (choose one)</label>
This should just be a general text element such as `p`, it isn't labelling a specific input.

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="radio" name="language" value="javascript" /> JavaScript
The text for each of these radio inputs should be a `label`

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +    <div><checkbox>
There is no such element as `checkbox`, you should remove that.

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +    <label for="signup">Would you like to sign up for more information?</label>
This `for` attribute here is correct, but the form control element it is paired with needs a matching `id` attribute with the same value.

2021-08-17 22:00 UTC, codingcodymiller commented on html-forms/index.html
> +    <label for="comments">Comments</label>
This `for` attribute here is correct, but the form control element it is paired with needs a matching `id` attribute with the same value.

2021-08-18 03:00 UTC, juliedumbrique commented
https://user-images.githubusercontent.com/72038937/129829817-d95ba3c7-4207-456c-93f0-e26e99074f49.mov

2021-08-18 16:06 UTC, codingcodymiller approved these changes

2021-08-18 16:55 UTC, merged