Completed html-web-page exercise - Julie Dumbrique
juliedumbrique/c0821-code-solutions pull request #9
Opened 2021-08-18 03:59 UTC by juliedumbrique

https://user-images.githubusercontent.com/72038937/129834740-98d016f9-beba-4a25-8440-672797eb0140.mov

2021-08-18 16:09 UTC, codingcodymiller requested changes
Great start here! A couple notes for you:

2021-08-18 16:09 UTC, codingcodymiller commented on html-web-page/index.html
> +  <label for="name"></label>
There is no text labelling this input, so no `label` element is necessary

2021-08-18 16:09 UTC, codingcodymiller commented on html-web-page/index.html
> +  <input type="submit" value="Submit">
Form control elements should always be children of a `form` element.

2021-08-19 06:09 UTC, juliedumbrique commented
<img width="674" alt="Screen Shot 2021-08-18 at 11 05 18 PM" src="https://user-images.githubusercontent.com/72038937/130016870-338fa3e3-1288-4fc0-b4cb-e69891a4d57e.png">

2021-08-19 23:51 UTC, codingcodymiller approved these changes
Great work!!

2021-08-20 05:03 UTC, merged